# This is a makefile. I'm sure we'll need / want this at some point

stock_predictor: main.o #and all other .o files involved
	gcc -Wall -o stock_predictor main.o

main.o: main.c #and other header files
	gcc -Wall -c main.c
